<a href="https://colab.research.google.com/github/Shin-Sangseok/Google_colab_practice/blob/main/label_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.preprocessing import LabelEncoder
import numpy as np 
import pandas as pd

In [3]:
### 라벨 인코딩할 컬럼이 1개인 경우 

In [4]:
계절 = ['봄','여름','가을','겨울'] #데이터프레임은 인덱스와 많은 시리즈들의 결합 

In [5]:
#df = index + Series들 
#Series = index + values(ndarray)

In [6]:
#df에서 하나의 열은 Series

In [7]:
data = pd.Series(계절)
data

0     봄
1    여름
2    가을
3    겨울
dtype: object

In [8]:
encoder = LabelEncoder()

In [9]:
encoder.fit(data) #encoding해줄 데이터를 정리해주는 개념 
#어떤 것을 어떤 번호로 인코딩해야할지 정하는 역할 
#가을(0), 겨울(1), 봄(2), 여름(3) 

LabelEncoder()

In [10]:
encoder.classes_ #ㄱ,ㄴ,ㄷ,ㄹ 순 

array(['가을', '겨울', '봄', '여름'], dtype=object)

In [11]:
변환할컬럼 = ['가을','겨울','봄','여름','봄','여름','겨울','봄','여름','봄','여름']

In [12]:
target = pd.Series(변환할컬럼)
target

0     가을
1     겨울
2      봄
3     여름
4      봄
5     여름
6     겨울
7      봄
8     여름
9      봄
10    여름
dtype: object

In [13]:
target2 = encoder.transform(target) #fit 시키고 transform 시키는 경우 
print(target2, type(target2))

[0 1 2 3 2 3 1 2 3 2 3] <class 'numpy.ndarray'>


In [14]:
#inverse: 거꾸로 되돌리다 
array1 = [1,3,4,5,7,8,9]
list.reverse(array1)
array1

[9, 8, 7, 5, 4, 3, 1]

In [15]:
target3 = encoder.inverse_transform(target2)
target3

array(['가을', '겨울', '봄', '여름', '봄', '여름', '겨울', '봄', '여름', '봄', '여름'],
      dtype=object)

In [16]:
##라벨 인코딩할 컬럼이 2-3개인 경우 

In [17]:
words = ['apple','summer','summer','spring','spring']
hobby = ['book', 'run','talk','coffee','song']

In [18]:
df = pd.DataFrame({
    'words':words,
    'hobby':hobby
})
df

words   hobby
0   apple    book
1  summer     run
2  summer    talk
3  spring  coffee
4  spring    song

In [19]:
encoder2 = LabelEncoder()

In [20]:
col = df.columns
col

Index(['words', 'hobby'], dtype='object')

In [21]:
for c in col:
    df[c] = encoder2.fit_transform(df[c]) #fit와 transform 동시에 시키는 경우 

In [22]:
df

words  hobby
0      0      0
1      2      2
2      2      4
3      1      1
4      1      3

In [23]:
#나이(100,200,300):연속적인 값들은 (연속적인 숫자는) 라벨 인코딩할 
                    #필요없이 그대로 사용하면 된다. 
                    #int라고 생각했던 것이 바껴서 들어가면 문제가 생긴 것임. 
#나이대(어린이, 성년, 노년):연속적인 숫자가 아님 => 라벨인코딩의 대상이 됨. 
                            #category를 가지고 있음. 

In [24]:
#원-핫 인코딩안해주고 라벨인코딩만 해줘도 잘 적용이 되면 이대로 적용해도 된다.ex)titanic
#라벨 인코딩한 결과를 가지고 제대로 학습이 안되면, 정확하게 소속을 표현하는
#원-핫 인코딩으로 바꿔줘야 한다.

In [25]:
##원-핫 인코딩##
##라벨 인코딩: 연속형이 아닌 데이터를 원하는 형태의 숫자로 바꾸어 주는 것. 
##             1)연속형이 아닌 데이터를 숫자로 변환: LabelEncoder
##             fit() -- transform()하는 경우와 fit_transform()으로 하는 경우가 있다. 
##             2)숫자로만 변환하는 경우, 컴퓨터는 연속형 숫자로 오해하여 연산을 수행을 해서 
##             의도치 않는(원하지 않는)결과가 나올 수 있다. 해당됨을 나타나게 하기 위해 
##             라벨의 갯수만큼 컬럼을 만들어주고 해당되는 라벨에 표시(1)로 해주는 방법을 사용 
##             라벨 인코딩에서 원-핫 인코딩이 자주 사용된다. 

In [26]:
data2 = pd.Series(['apple','summer','spring','summer','spring'])
data2

0     apple
1    summer
2    spring
3    summer
4    spring
dtype: object

In [27]:
data2.unique() 

array(['apple', 'summer', 'spring'], dtype=object)

In [28]:
pd.get_dummies(data2)

apple  spring  summer
0      1       0       0
1      0       0       1
2      0       1       0
3      0       0       1
4      0       1       0

In [29]:
df2 = pd.DataFrame({"words" : ['apple', 'summer', 'summer', 'spring', 'spring'], 
                    "hobby" : ['book', 'run','talk','coffee','song']})
df2

words   hobby
0   apple    book
1  summer     run
2  summer    talk
3  spring  coffee
4  spring    song

In [30]:
pd.get_dummies(df2['hobby'])

book  coffee  run  song  talk
0     1       0    0     0     0
1     0       0    1     0     0
2     0       0    0     0     1
3     0       1    0     0     0
4     0       0    0     1     0

In [31]:
df2.loc[:,['words','hobby']]

words   hobby
0   apple    book
1  summer     run
2  summer    talk
3  spring  coffee
4  spring    song

In [33]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [34]:
import pandas as pd 
csv_data = pd.read_csv('/content/drive/MyDrive/drinks.csv')
csv_data

#df = pd.read_csv('/content/scientists.csv')
#df
#/content/drive/MyDrive/python-data/scientists.csv

country  beer_servings  spirit_servings  wine_servings  \
0    Afghanistan              0                0              0   
1        Albania             89              132             54   
2        Algeria             25                0             14   
3        Andorra            245              138            312   
4         Angola            217               57             45   
..           ...            ...              ...            ...   
188    Venezuela            333              100              3   
189      Vietnam            111                2              1   
190        Yemen              6                0              0   
191       Zambia             32               19              4   
192     Zimbabwe             64               18              4   

     total_litres_of_pure_alcohol continent  
0                             0.0        AS  
1                             4.9        EU  
2                             0.7        AF  
3                            12.4        EU  
4                             5.9        AF  
..                            ...       ...  
188                           7.7        SA  
189                           2.0        AS  
190                           0.1        AS  
191                           2.5        AF  
192                           4.7        AF  

[193 rows x 6 columns]

# 새 섹션

In [35]:
df_samples =csv_data.loc[:,['beer_servings', 'continent']]
df_samples

beer_servings continent
0                0        AS
1               89        EU
2               25        AF
3              245        EU
4              217        AF
..             ...       ...
188            333        SA
189            111        AS
190              6        AS
191             32        AF
192             64        AF

[193 rows x 2 columns]

In [36]:
#beer_servings를 세개 의 그룹으로 나누기. [o]
#그룹으로 만들어서 1번의 결과를 beer_cat 변수로 추가[o] 
#Label Encoding 2가지 방식으로 [o]
#원핫인코딩 df전체 
#특정 컬럼(1개 또는 그 이상)선택해서 원핫 인코딩 

In [37]:
#pclass는 숫자가 크고 작음에 따라서 차이가 있음. 
#gender는 0에 속하느냐 1에 속하느냐의 차이이지 차이는 없다. 
#gender 같으 경우에는 차이를 넣어야하기 때문에 원-핫 인코딩을 해야 하고 
#pclass는 숫자에 따라 차이가 존재하기 때문에 해도 되고 안해줘도 된다. 
#숫자가 크기에 차이가 반영되어 있다면 원-핫 인코딩까지는 안해도 된다. 

In [38]:
df_samples['beer_servings'].describe() # 25% 20.0 50% 76.0 75% 188.0 max 376.0 

count    193.000000
mean     106.160622
std      101.143103
min        0.000000
25%       20.000000
50%       76.000000
75%      188.000000
max      376.000000
Name: beer_servings, dtype: float64

In [39]:
df_samples['beer_servings'] = pd.cut(
                            df_samples['beer_servings'], 
                            bins = [0,76,188,376],
                            include_lowest=  True,  
                            labels = ['low','middle','high']
                        )
df_samples


beer_servings continent
0             low        AS
1          middle        EU
2             low        AF
3            high        EU
4            high        AF
..            ...       ...
188          high        SA
189        middle        AS
190           low        AS
191           low        AF
192           low        AF

[193 rows x 2 columns]

In [40]:
encoder = LabelEncoder()
#beer_cat = 


In [41]:
encoder.fit(df_samples['beer_servings'])

LabelEncoder()

In [42]:
encoder.classes_

array(['high', 'low', 'middle'], dtype=object)

In [43]:
change_col = df_samples['beer_servings']
target = pd.Series(change_col)

In [44]:
target

0         low
1      middle
2         low
3        high
4        high
        ...  
188      high
189    middle
190       low
191       low
192       low
Name: beer_servings, Length: 193, dtype: category
Categories (3, object): ['low' < 'middle' < 'high']

In [54]:
df_samples2 = df_samples.copy()
del df_samples2['beer_cat']
df_samples2

beer_servings continent
0             low        AS
1          middle        EU
2             low        AF
3            high        EU
4            high        AF
..            ...       ...
188          high        SA
189        middle        AS
190           low        AS
191           low        AF
192           low        AF

[193 rows x 2 columns]

In [45]:
target2 = encoder.transform(target)
df_samples['beer_cat'] = target2

In [46]:
print(encoder.inverse_transform(df_samples['beer_cat']))

['low' 'middle' 'low' 'high' 'high' 'middle' 'high' 'low' 'high' 'high'
 'low' 'middle' 'low' 'low' 'middle' 'middle' 'high' 'high' 'low' 'low'
 'middle' 'low' 'middle' 'high' 'low' 'high' 'low' 'middle' 'low' 'middle'
 'low' 'middle' 'high' 'low' 'low' 'middle' 'middle' 'middle' 'low' 'low'
 'low' 'middle' 'high' 'middle' 'high' 'high' 'low' 'low' 'high' 'low'
 'low' 'high' 'middle' 'low' 'low' 'middle' 'low' 'high' 'low' 'middle'
 'high' 'middle' 'high' 'low' 'low' 'high' 'low' 'middle' 'high' 'low'
 'low' 'low' 'middle' 'low' 'low' 'high' 'high' 'low' 'low' 'low' 'low'
 'high' 'low' 'middle' 'middle' 'middle' 'low' 'middle' 'low' 'low' 'low'
 'low' 'low' 'high' 'low' 'middle' 'low' 'low' 'high' 'high' 'low' 'low'
 'low' 'low' 'low' 'middle' 'low' 'low' 'middle' 'high' 'low' 'low'
 'middle' 'low' 'low' 'low' 'low' 'high' 'low' 'low' 'high' 'high'
 'middle' 'low' 'low' 'middle' 'middle' 'low' 'low' 'high' 'high' 'low'
 'high' 'middle' 'low' 'high' 'high' 'low' 'middle' 'middle' 'high'

In [47]:
df_samples

beer_servings continent  beer_cat
0             low        AS         1
1          middle        EU         2
2             low        AF         1
3            high        EU         0
4            high        AF         0
..            ...       ...       ...
188          high        SA         0
189        middle        AS         2
190           low        AS         1
191           low        AF         1
192           low        AF         1

[193 rows x 3 columns]

In [48]:
encoder2 = LabelEncoder()
encoder2

LabelEncoder()

In [49]:
col = df_samples['continent']
col

0      AS
1      EU
2      AF
3      EU
4      AF
       ..
188    SA
189    AS
190    AS
191    AF
192    AF
Name: continent, Length: 193, dtype: object

In [50]:
col.unique()

array(['AS', 'EU', 'AF', nan, 'SA', 'OC'], dtype=object)

In [51]:
pd.get_dummies(col)

AF  AS  EU  OC  SA
0     0   1   0   0   0
1     0   0   1   0   0
2     1   0   0   0   0
3     0   0   1   0   0
4     1   0   0   0   0
..   ..  ..  ..  ..  ..
188   0   0   0   0   1
189   0   1   0   0   0
190   0   1   0   0   0
191   1   0   0   0   0
192   1   0   0   0   0

[193 rows x 5 columns]

In [55]:
pd.get_dummies(df_samples2)

beer_servings_low  beer_servings_middle  beer_servings_high  \
0                    1                     0                   0   
1                    0                     1                   0   
2                    1                     0                   0   
3                    0                     0                   1   
4                    0                     0                   1   
..                 ...                   ...                 ...   
188                  0                     0                   1   
189                  0                     1                   0   
190                  1                     0                   0   
191                  1                     0                   0   
192                  1                     0                   0   

     continent_AF  continent_AS  continent_EU  continent_OC  continent_SA  
0               0             1             0             0             0  
1               0             0             1             0             0  
2               1             0             0             0             0  
3               0             0             1             0             0  
4               1             0             0             0             0  
..            ...           ...           ...           ...           ...  
188             0             0             0             0             1  
189             0             1             0             0             0  
190             0             1             0             0             0  
191             1             0             0             0             0  
192             1             0             0             0             0  

[193 rows x 8 columns]

In [56]:
df_samples2

beer_servings continent
0             low        AS
1          middle        EU
2             low        AF
3            high        EU
4            high        AF
..            ...       ...
188          high        SA
189        middle        AS
190           low        AS
191           low        AF
192           low        AF

[193 rows x 2 columns]

In [57]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

str = '원 핫 인코딩은 단어를 표현하는 가장 기본적인 방법이며, 머신러닝, 딥러닝을 위해서는 반드시 배워야 하는 표현 방법입니다.'
  


In [59]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([str])
print(tokenizer.word_index)

{'원': 1, '핫': 2, '인코딩은': 3, '단어를': 4, '표현하는': 5, '가장': 6, '기본적인': 7, '방법이며': 8, '머신러닝': 9, '딥러닝을': 10, '위해서는': 11, '반드시': 12, '배워야': 13, '하는': 14, '표현': 15, '방법입니다': 16}


In [61]:
encoded = tokenizer.texts_to_sequences([str])[0]
print(encoded)

#tokenizer에는 단어별 인덱스값이 저장된 상태이며, 
#text_to_sequences에 문장을 넣으면 문장의 내용을
#인덱스 배열로 리턴하게 된다 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]


In [64]:
onehot = tf.keras.utils.to_categorical(encoded)
print(onehot)
#케라스에서 to_categorical함수에 배열값을 전달하면 원핫 인코딩을 할 수 있다.

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [65]:
onehot = tf.keras.utils.to_categorical(encoded, 20)#범위 지정 
print(onehot)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.